### PR TITLE
22 implement app flow with dummy data from backend server

### LINKED ISSUE #22: implement app flow with dummy data from backend server
- We still likely can't use auth yet, so maybe implement from login page and have the login just go to the session select page
- Once on the session select page, after a user selects their preferences this needs to send a axios request (check out the requests in the `api` folder) will likely have to create some sort of request object to use
- Display a loading spinner in the button or center screen
- Once loaded the questions display them in the card component

### PR DESCRIPTION
**Pull request by michael-duren**
- Created user flow
- Simplified multi choice component
- Added api fetching

### CODE REVIEW

**Comment by quynhngandao** [comment]
```
SessionFormContext.tsx

export type Difficulty = 'Easy' | 'Med' | 'Hard' | 'Pro';
```

```
NewSessionDto.ts

export interface NewSessionDto {
  topic: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
}
```

Was just wondering if these need to match or doesn't matter

**Comment by michael-duren** [comment]
Updated.

**Comment by michael-duren** [comment]
Good catch

**Comment by quynhngandao** [comment]
1. file name change MultipleChoice.tsx to multipleChoice
2. cannot update a component error after 3rd question
image

**Review by quynhngandao — APPROVED** [review]
tested and working

**Pull request merged**
